name: Verse Planter

on:
  push:
    branches:
      - green
  schedule:
    - cron: '0 6 * * *'  # KST 15시
  workflow_dispatch:

permissions:
  contents: write

jobs:
  poetry-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.name "2dam0"
          git config --global user.email "yidamyeong@gmail.com"
      - name: Run poet
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          chmod +x poet.sh
          ./poet.sh
