name: Verse Planter

on:
  schedule:
    - cron: '*/5 * * * *'  # 매 5분마다 실행 (테스트용)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config user.name "2dam0"
          git config user.email "yidamyeong@gmail.com"
      - name: Run poet
        run: |
          chmod +x poet.sh
          ./poet.sh