name: Verse Planter

on:
  push:
    branches:
      - green
  schedule:
    - cron: '0 22 * * *'  # KST 오전 7시
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.name "damyeong"
          git config --gloabl user.email "yidamyeong@gmail.com"
      - name: Run poet
        run: |
          chmod +x poet.sh
          ./poet.sh
